name: aqueduct
version: 4.0.0-b1
description: A modern HTTP server application framework, ORM and OAuth2 provider with OpenAPI 3.0 integration. Foundation for REST, RPC or GraphQL services.
homepage: https://aqueduct.io
documentation:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  analyzer: ^1.1.0
  crypto: ^3.0.0
  logging: ^1.0.0
  isolate_executor:
    git: https://github.com/j4qfrost/dart-isolate-executor
  open_api:
    git: https://github.com/j4qfrost/open-api-dart
  password_hash:
    git: https://github.com/Derrick56007/dart-password-hash
  path: ^1.8.0
  postgres:
    git: https://github.com/j4qfrost/postgresql-dart
  pub_cache:
    git: https://github.com/j4qfrost/pub_cache
  pub_semver: ^2.0.0
  safe_config:
    git: https://github.com/j4qfrost/safe_config
  yaml: ^3.1.0
  runtime:
    git: https://github.com/j4qfrost/dart-runtime.git

dev_dependencies:
  matcher: ^0.12.10
  test: ^1.16.5
  http: ^0.13.0
  command_line_agent:
    git: https://github.com/j4qfrost/dart-test-terminal
  aqueduct_test:
    path: ../aqueduct_test

executables:
  aqueduct: aqueduct