name: aqueduct
version: 3.0.0
description: A modern HTTP server application framework, ORM and OAuth2 provider with OpenAPI 3.0 integration. Foundation for REST, RPC or GraphQL services.
author: stable|kernel <http://stablekernel.com>
homepage: https://aqueduct.io
documentation:

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  analyzer: '>=0.32.0 <0.33.0'
  args: ^1.5.0
  crypto: ^2.0.6
  logging: ^0.11.3
  isolate_executor: ^2.0.0
  meta: ^1.1.5
  open_api: ^2.0.0
  password_hash: ^2.0.0
  path: ^1.6.1
  postgres: ^1.0.0
  pub_cache: '>=0.2.0 <0.3.0'
  pub_semver: ^1.4.0
  safe_config: ^2.0.0
  yaml: ^2.1.15

dev_dependencies:
  matcher: ^0.12.3
  test: ^1.3.0
  http: ^0.11.3+7
  aqueduct_test:
    path: ../aqueduct_test

executables:
  aqueduct: aqueduct