branches:
  only:
    - master
    - 3.0

services:
  - postgresql96

environment:
  matrix:
  - TEST_DIR: aqueduct_test
  - TEST_DIR: aqueduct

install:
  - ps: wget https://storage.googleapis.com/dart-archive/channels/dev/release/latest/sdk/dartsdk-windows-x64-release.zip -OutFile dart-sdk.zip
  - cmd: echo "Unzipping dart-sdk..."
  - cmd: 7z x dart-sdk.zip -o"C:\tools" -y > nul
  - set PATH=%PATH%;C:\tools\dart-sdk\bin
  - set PATH=%PATH%;%APPDATA%\Pub\Cache\bin
  - set PGUSER=postgres
  - set PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
  - cmd: psql -U postgres -c "create user dart with createdb;"
  - cmd: psql -U postgres -c "alter user dart with password 'dart';"
  - cmd: psql -U postgres -c "create database dart_test;"
  - cmd: psql -U postgres -c "grant all on database dart_test to dart;"

build: off

test_script:
  - cmd: cd %TEST_DIR%
  - cmd: pub get
  - cmd: pub run test -j1

cache:
  - C:\Users\appveyor\AppData\Roaming\Pub\Cache