name: aqueduct
version: 1.0.0+1
description: A fully featured server-side framework built for productivity and testability.
author: stable|kernel <http://stablekernel.com>
homepage: https://github.com/stablekernel/aqueduct
documentation:

environment:
  sdk: ">=1.20.0 <2.0.0"

dependencies:
  safe_config: ">=1.1.0 <2.0.0"
  yaml: ">=2.1.9 <3.0.0"
  matcher: ">=0.12.0+2 <0.13.0"
  crypto: "^2.0.0"
  logging: ">=0.11.3 <0.12.0"
  analyzer: ">=0.28.0 <0.30.0"
  postgres: ">=0.9.1 <1.0.0"
  args: ">=0.13.5 <1.0.0"

dev_dependencies:
  test: any
  http: ">=0.11.3+7 <0.12.0"

executables:
  aqueduct: aqueduct