name: aqueduct
version: 3.0.0
description: Server-side framework, including routing, ORM and OAuth 2.0 in a consistent, rigorously tested framework.
author: stable|kernel <http://stablekernel.com>
homepage: https://aqueduct.io
documentation:

environment:
  sdk: ^2.0.0-dev

dependencies:
  analyzer: '>=0.30.0 <0.32.0'
  args: ^1.0.0
  crypto: ^2.0.0
  logging: ^0.11.3
  matcher: ^0.12.0+2
  open_api: ^1.0.2
  password_hash: ^1.0.0
  path: ^1.4.1
  postgres: ^0.9.6
  pub_cache: ^0.1.0
  pub_semver: ^1.0.0
  safe_config: ^1.1.0
  stack_trace: ^1.0.0
  test: ^0.12.28
  yaml: ^2.1.9

dev_dependencies:
  http: ^0.11.3+7

executables:
  aqueduct: aqueduct
