name: aqueduct_test
description: Utilities for writing automated tests for Aqueduct applications
version: 1.0.0-beta.1
homepage: https://github.com/stablekernel/aqueduct
author: stable|kernel <jobs@stablekernel.com>
documentation:

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  test: ^1.0.0
  matcher: ^0.12.0+2
  aqueduct: ^3.0.0-beta.1

# This is removed before being published.
dependency_overrides:
  aqueduct:
    path: ../aqueduct