name: aqueduct_test
description: Utilities to write tests for aqueduct applications
version: 1.0.0
homepage: https://github.com/stablekernel/aqueduct
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  test: ^0.12.0
  matcher: ^0.12.0+2
  aqueduct: ^3.0.0

dependency_overrides:
  aqueduct:
    path: ../aqueduct