name: wildfire
description: An Aqueduct application with a database connection and data model.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  aqueduct: ^3.0.0

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  aqueduct_test:
    git:
      url: https://github.com/stablekernel/aqueduct_test.git
      ref: master

