name: wildfire
description: An Aqueduct application with a database connection, data model and OAuth 2.0 endpoints.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  aqueduct: ^3.0.0

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
