name: aqueduct_doc_tools
version: 0.0.1
description: Tools
author: stable|kernel <http://stablekernel.com>
homepage: https://github.com/stablekernel/aqueduct

environment:
  sdk: ">=1.20.0 <2.0.0"

dependencies:
  args: any
