name: wildfire
description: A web server application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  scribe: any
  aqueduct: ">=1.0.0 <1.1.0"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
