site_name: Aqueduct
theme: 'material'
markdown_extensions:
  - codehilite
  - markdown.extensions.admonition
extra_css:
  - style/css/override.css
repo_url: https://github.com/stablekernel/aqueduct
google_analytics: ['UA-41269877-2', 'aqueduct.io']
site_description: Documentation for Aqueduct, a Dart server-side framework.
copyright: Built by stable|kernel
pages:
- Home: 'index.md'
- Getting Started: 'getting_started.md'
- Tour: 'tour.md'
- IntelliJ IDEA Templates: 'intellij.md'
- Snippets:
  - 'Overview': 'snippets/overview.md'
  - 'HTTP': 'snippets/http.md'
  - 'ORM': 'snippets/orm.md'
  - 'Authentication and Authorization': 'snippets/auth.md'
  - 'Testing': 'snippets/test.md'
- Tutorial:
  - '1. Getting Started': 'tut/getting-started.md'
  - '2. Reading from a Database': 'tut/executing-queries.md'
  - '3. Storing Data in a Database': 'tut/storing-data.md'
  - '4. Writing Tests': 'tut/writing-tests.md'
  - '5. Deploying': 'tut/deploying-and-other-fun-things.md'
- Guides:
  - Serving HTTP Requests:
    - 'Overview': 'http/overview.md'
    - 'Application Structure': 'http/structure.md'
    - 'Request and Response Objects': 'http/request_and_response.md'
    - 'Handling Requests: Fundamentals': 'http/controller.md'
    - 'Routing': 'http/routing.md'
    - 'Initialization and the ApplicationChannel': 'http/channel.md'
    - 'Handling Requests: ResourceController': 'http/resource_controller.md'
    - 'Configuration': 'http/configure.md'
    - 'Serving Files and Caching': 'http/serving_files.md'
    - 'Websockets': 'http/websockets.md'
    - 'Multi-threading': 'http/threading.md'
  - Databases and ORM:
    - 'Overview': 'db/overview.md'
    - 'Connecting to a Database': 'db/connecting.md'
    - 'Modeling Data': 'db/modeling_data.md'
    - 'Storage, Serialization and Deserialization': 'db/serialization.md'
    - 'Executing Queries': 'db/executing_queries.md'
    - 'Advanced Queries': 'db/advanced_queries.md'
    - 'Validations': 'db/validations.md'
    - 'Migration and Tooling': 'db/db_tools.md'
  - Authorization and OAuth 2.0:
    - 'Overview': 'auth/overview.md'
    - 'Setting up Authorization': 'auth/server.md'
    - 'Protecting Routes': 'auth/authorizer.md'
    - 'Issuing Access Tokens': 'auth/controllers.md'
    - 'Managing OAuth 2.0 Clients': 'auth/cli.md'
    - 'OAuth 2.0 Scoping': 'auth/auth_scopes.md'
    - 'What is OAuth 2.0?': 'auth/what_is_oauth.md'
  - Development and Testing:
    - 'Overview': 'testing/overview.md'
    - 'Using a Local Database': 'testing/database.md'
    - 'Using the Debugger': 'testing/debugger.md'
    - 'Development Best Practices': 'testing/best_practices.md'
    - 'Developing Client Applications': 'testing/clients.md'
    - 'Writing Tests': 'testing/tests.md'
    - 'Mocking Services'  : 'testing/mock.md'
  - Deployment:
    - 'Overview': 'deploy/overview.md'
    - 'Deploy Locally': 'deploy/deploy_local.md'
    - 'Deploy on Heroku': 'deploy/deploy_heroku.md'
    - 'Deploy on AWS': 'deploy/deploy_aws.md'
    - 'Deploying without aqueduct serve': 'deploy/script.md'
  - Command-line Tooling:
    - 'Overview': 'cli/overview.md'
    - 'Creating Applications': 'cli/create.md'
    - 'Running Applications': 'cli/running.md'
    - 'Generating an OpenAPI/Swagger Specification': 'cli/document.md'
    - 'Other Tools': 'cli/setup.md'
