site_name: Aqueduct
theme:
  name: material
  custom_dir: overrides
markdown_extensions:
  - codehilite
  - markdown.extensions.admonition
extra_css:
  - style/css/override.css
repo_url: https://github.com/stablekernel/aqueduct
edit_uri: edit/docs/source/source/docs/
google_analytics: ['UA-41269877-2', 'aqueduct.io']
site_description: Documentation for Aqueduct, a Dart server-side framework.
copyright: Built by Stable Kernel
pages:
- Home: 'index.md'
- Core Concepts: 'core_concepts.md'
- Getting Started: 'getting_started.md'
- Tour: 'tour.md'
- Best Practices: 'best_practices.md'
- IntelliJ IDEA Templates: 'intellij.md'
- Tutorial:
  - '1. Getting Started': 'tut/getting-started.md'
  - '2. Reading from a Database': 'tut/executing-queries.md'
  - '3. Storing Data in a Database': 'tut/storing-data.md'
  - '4. Configuration and Testing': 'tut/writing-tests.md'
  - '5. Authentication and Authorization': 'tut/oauth2.md'
- Snippets:
  - 'Overview': 'snippets/index.md'
  - 'HTTP': 'snippets/http.md'
  - 'ORM': 'snippets/orm.md'
  - 'Authentication and Authorization': 'snippets/auth.md'
  - 'Testing': 'snippets/test.md'  
- 'Guide: Application Configuration and Behavior':
  - 'Overview': 'application/index.md'
  - 'Starting and Stopping Applications': 'application/channel.md'
  - 'Configuring an Application and its Environment': 'application/configure.md'
  - 'Application and Project Structure': 'application/structure.md'
  - 'Multi-threading': 'application/threading.md'
- 'Guide: Handling HTTP Requests':
  - 'Overview': 'http/index.md'
  - 'Handling Requests and Sending Response': 'http/controller.md'
  - 'Serializing Request and Response Bodies': 'http/request_and_response.md'
  - 'Routing': 'http/routing.md'
  - 'Request Binding with Resource Controllers': 'http/resource_controller.md'
  - 'Serving Files and Caching': 'http/serving_files.md'
  - 'Websockets': 'http/websockets.md'
  - 'Uploading Files': 'http/file_upload.md'
- 'Guide: Databases and ORM':
  - 'Overview': 'db/index.md'
  - 'Connecting to a Database': 'db/connecting.md'
  - 'Modeling Data and Relationships': 'db/modeling_data.md'
  - 'Serialization and Deserialization': 'db/serialization.md'
  - 'Basic Queries': 'db/executing_queries.md'
  - 'Advanced Queries': 'db/advanced_queries.md'
  - 'Transactions': 'db/transactions.md'
  - 'Validations': 'db/validations.md'
  - 'Migration and Tooling': 'db/db_tools.md'
  - 'JSON Document Storage': 'db/json_columns.md'
- 'Guide: Authorization and OAuth 2.0':
  - 'Overview': 'auth/index.md'
  - 'Setting up Authorization': 'auth/server.md'
  - 'Protecting Routes': 'auth/authorizer.md'
  - 'Issuing Access Tokens': 'auth/controllers.md'
  - 'Managing OAuth 2.0 Clients': 'auth/cli.md'
  - 'OAuth 2.0 Scoping': 'auth/auth_scopes.md'
  - 'What is OAuth 2.0?': 'auth/what_is_oauth.md'
- 'Guide: Development and Testing':
  - 'Overview': 'testing/index.md'
  - 'Writing Tests': 'testing/tests.md'
  - 'Testing with the ORM and OAuth 2.0': 'testing/mixins.md'
  - 'Using the Debugger': 'testing/debugger.md'
  - 'Developing Client Applications': 'testing/clients.md'
  - 'Mocking Services': 'testing/mock.md'
- 'Guide: OpenAPI Documentation':
  - 'Overview': 'openapi/index.md'
  - 'Creating an OpenAPI Document': 'openapi/cli.md'
  - 'Documenting Components': 'openapi/components.md'
  - 'Documenting Endpoint Controllers': 'openapi/endpoint.md'
  - 'Documenting Middleware Controllers': 'openapi/middleware.md'
- 'Guide: Command-line Tooling':
  - 'Overview': 'cli/index.md'
  - 'Creating Applications': 'cli/create.md'
  - 'Running Applications': 'cli/running.md'
  - 'Generating an OpenAPI/Swagger Specification': 'cli/document.md'
- 'Guide: Deployment':
  - 'Overview': 'deploy/index.md'
  - 'Creating an Aqueduct Executable': 'deploy/build.md'
  - 'Deploy Locally (VM)': 'deploy/deploy_local.md'
  - 'Deploying with Docker and Kubernetes (VM)': 'deploy/deploy_docker.md'
  - 'Deploy on Heroku (VM)': 'deploy/deploy_heroku.md'
  - 'Deploy on AWS (VM)': 'deploy/deploy_aws.md'
  - 'Deploying without aqueduct serve (VM)': 'deploy/script.md'
